<div class="wrap">
  <div id="icon-options-general" class="icon32"><br/></div>

  <h2>Cart66 Cloud Settings</h2>

  <form action="" method="post">
    <?php wp_nonce_field('save_settings', 'cc_nonce'); ?>
    <input type="hidden" name="cc_task" value="admin_save_settings">

    <table class="form-table">
      <tr valign="top">
        <th scope="row"><label for="cc_secret_key"><?php _e('Cart66 Cloud Secret Key', 'cart66'); ?></label></th>
        <td><input name="cc_settings[cc_secret_key]" type="text" id="cc_secret_key" value="<?php echo get_site_option('cc_secret_key'); ?>" class="regular-text" /></td>
      </tr>

      <tr valign="top">
        <th scope="row"><label for="cc_redirect_type"><?php _e('Add to cart redirect', 'cart66'); ?></label></th>
        <td>
          <fieldset><legend class="screen-reader-text"><span><?php _e('After adding a product to the cart', 'cart66'); ?></span></legend>
            <label title="stay">
              <input type="radio" name="cc_settings[cc_redirect_type]" id="cc_redirect_type_stay" value="stay" <?php echo $redirect_type  == 'stay' ? 'checked="checked"' : ''; ?>>
              <span><?php _e('Stay on same page', 'cart66'); ?></span>
            </label>
            <br/>
            <label title="view cart">
              <input type="radio" name="cc_settings[cc_redirect_type]" id="cc_redirect_type_view_cart" value="view_cart" <?php echo $redirect_type  == 'view_cart' ? 'checked="checked"' : ''; ?>>
              <span><?php _e('Go to view cart page', 'cart66'); ?></span>
            </label>
            <br/>
            <label title="checkout page">
              <input type="radio" name="cc_settings[cc_redirect_type]" id="cc_redirect_type_checkout" value="checkout" <?php echo $redirect_type  == 'checkout' ? 'checked="checked"' : ''; ?>>
              <span><?php _e('Go to checkout page', 'cart66'); ?></span>
            </label>
          </fieldset>
          <p class="description"><?php _e('Where to direct the buyer after adding a product to the shopping cart', 'cart66'); ?></p>
        </td>
      </tr>

      <tr valign="top">
        <th scope="row"><label for="cc_product_loader"><?php _e('Product loader', 'cart66'); ?></label></th>
        <td>
          <fieldset><legend class="screen-reader-text"><span><?php _e('Server API call', 'cart66'); ?></span></legend>
            <label>
              <input type="radio" name="cc_settings[cc_product_loader]" id="cc_product_loader_server" value="server" <?php echo $product_loader  == 'server' ? 'checked="checked"' : ''; ?>>
              <span><?php _e('Server side loading', 'cart66'); ?></span>
            </label>
            <br/>
            <label>
              <input type="radio" name="cc_settings[cc_product_loader]" id="cc_product_loader_client" value="client" <?php echo $product_loader  == 'client' ? 'checked="checked"' : ''; ?>>
              <span><?php _e('Client side loading via AJAX (faster but requires javascript)', 'cart66'); ?></span>
            </label>
          </fieldset>
        </td>
      </tr>

      <tr>
        <th scope="row"><label for="cc_page_slurp_mode"><?php _e('Page Slurp Mode', 'cart66'); ?></label></th>
        <td>
          <select name="cc_settings[cc_page_slurp_mode]" id="cc_settings_cc_page_slurp_mode">
            <option value="physical" <?php echo $slurp_mode == 'physical' ? 'selected="selected"' : '' ?>>Physical Page</option>
            <option value="virtual"  <?php echo $slurp_mode == 'virtual' ? 'selected="selected"' : '' ?>>Virtual Page</option>
          </select>
          <p class="description"><?php _e('Physical page mode recommended', 'cart66'); ?></p>
        </td>
      </tr>


      <?php if($slurp_mode == 'virtual'): ?>
      <tr>
        <th scope="row"><label for="cc_selected_page_template"><?php _e('Virtual page template', 'cart66'); ?></label></th>
        <td>
          <select name="cc_settings[cc_selected_page_template]" id="cc_settings_cc_selected_page_template">
            <?php foreach($templates as $file => $description): ?>
              <?php CC_Log::write('[' . basename(__FILE__) . ' - line ' . __LINE__ . "] Comparing file to selected page: file = $file :: $selected_page_template"); ?>
              <option value="<?php echo $file; ?>" <?php echo $file == $selected_page_template ? 'selected="selected"' : ''; ?>><?php echo $description; ?></option>
            <?php endforeach; ?>
          </select>
          <p class="description"><?php _e('If you are using Virtual Page mode, which page template would you like to use on Cart66 Cloud', 'cart66'); ?></p>
        </td>
      </tr>
      <?php endif; ?>

      <tr validn-"top">
        <th scope="row"><?php _e('Your custom subdomain', 'cart66'); ?></th>
        <td>
          <?php 
            $subdomain = CC_Library::get_subdomain(); 
            echo $subdomain ? $subdomain : 'Not set';
          ?>
          <p class="description"><?php _e('Your custom subdomain is set on the Settings tab of your <a href="https://manage.cart66.com">Cart66 Cloud management console.</a><br>Set your subdomain there, then click this button to update the subdomain value for your WordPress store.', 'cart66'); ?></p>
          <p><input type="submit" name="submit" id="submit" class="button-secondary" value="Sync Subdomain"></p>
        </td>
      </tr>

      <tr valign="top">
        <th scope="row"><label for="cc_logging"><?php _e('Debugging', 'cart66'); ?></label></th>
        <td>
          <fieldset><legend class="screen-reader-text"><span><?php _e('Debugging', 'cart66'); ?></span></legend>
            <label title="yes">
              <input type="radio" name="cc_settings[cc_logging]" id="cc_logging_yes" value="1" <?php echo $logging  == 1 ? 'checked="checked"' : ''; ?>>
              <span><?php _e('Yes', 'cart66'); ?></span>
            </label>
            &nbsp;
            <label title="no">
              <input type="radio" name="cc_settings[cc_logging]" id="cc_logging_no" value="0" <?php echo $logging  == 0 ? 'checked="checked"' : ''; ?>>
              <span><?php _e('No', 'cart66'); ?></span>
            </label>
          </fieldset>
          <p class="description"><?php _e('Enable logging of debug and error messages in the log.txt file of the Cart66 Cloud plugin.<br/> Be careful, the log gets big quick. Only use for testing.', 'cart66'); ?></p>
          <p>
            <a href='?page=cart66&cc_task=download_log' class="button"><?php _e('Download Log File', 'cart66'); ?></a>
            <a href='?page=cart66&cc_task=reset_log' class="button"><?php _e('Reset Log File', 'cart66'); ?></a>
            <a href='?page=cart66&cc_task=test_remote_calls' class="button"><?php _e('Test Remote Calls', 'cart66'); ?></a>
          </p>

          <?php if(CC_FlashData::exists('task_message')): ?>
            <p class="description"><?php echo CC_FlashData::get('task_message'); ?></p>
          <?php endif; ?>
            
          <?php if(CC_FlashData::exists('remote_call_test_results')): ?>
            <p class="description"><?php echo CC_FlashData::get('remote_call_test_results'); ?></p>
          <?php endif; ?>
        </td>
      </tr>
    </table>

    <p class="submit"><input type="submit" name="submit" id="submit" class="button-primary" value="Save Changes"></p>
  </form>
</div>
