<?php wp_nonce_field('ccm_save_membership_ids', 'ccm_membership_ids_nonce'); ?>

<?php if(is_array($memberships) && count($memberships) > 0): ?>
  <div class="misc-pub-section">
    Select the memberships that are required to view this content.

    <ul>
      <?php foreach($memberships as $m): ?>
      <?php
        $name = $m['name'];
        $sku = $m['sku'];
      ?>
      <?php $checked = (is_array($requirements) && in_array($sku, $requirements)) ? 'checked="checked"' : ''; ?>
      <li>
        <?php if(!empty($sku)): ?>
        <input type="checkbox" name="ccm_membership_ids[]" value="<?php echo $sku; ?>" <?php echo $checked; ?> />
        <?php endif; ?>
        <?php echo $name; ?>
      </li>
      <?php endforeach; ?>
    </ul>
    
  </div>

  <?php if($post_type != 'post'): ?>
    <div class="misc-pub-section">
      <p><strong>Access Denied Page</strong></p>
      <p>If you don't use an access denied page, the content of the page will be replaced with your <a href='admin.php?page=cart66_members'>access notifications</a>.</p>

      <?php 
        $args = array(
          'name' => '_ccm_access_denied_page_id',
          'show_option_none' => __('Do not use an access denied page', 'cart66'),
          'option_none_value' => '0',
          'selected' => $access_denied_page_id
        );
        wp_dropdown_pages($args); 
       ?>
    </div>

  <div class="misc-pub-section">
  <?php else: ?>
  <div class="misc-pub-section" style="border-bottom: none;">
  <?php endif; ?>
    <p><strong>Deny access for</strong></p>
    <p>
      <label class="screen-reader-text" for="days_in">Days in</label>
      <input name="_ccm_days_in" type="text" size="4" id="_ccm_days_in" value="<?php echo $days; ?>" /> days after subscription starts
    </p>
  </div>

  <?php if($post_type != 'post'): ?>
  <div class="misc-pub-section" style="border-bottom: none;">
    <p><strong>Page Display Override</strong></p>
    <p>By default a page that requires a membership is hidden from the navigation when the visitor is logged out. 
       Use these settings to override the default behavior.</p>

    <p><strong>When visitor is logged in</strong></p>

    <select name="_ccm_when_logged_in">
      <option value="" <?php if($when_logged_in == '') { echo 'selected="selected"'; } ?>>Default behavior</option>
      <option value="show" <?php if($when_logged_in == 'show') { echo 'selected="selected"'; } ?>>Show page</option>
      <option value="hide" <?php if($when_logged_in == 'hide') { echo 'selected="selected"'; } ?>>Hide page</option>
    </select>

    <p><strong>When visitor is logged out</strong></p>

    <select name="_ccm_when_logged_out">
      <option value="" <?php if($when_logged_out == '') { echo 'selected="selected"'; } ?>>Default behavior</option>
      <option value="show" <?php if($when_logged_out == 'show') { echo 'selected="selected"'; } ?>>Show page</option>
      <option value="hide" <?php if($when_logged_out == 'hide') { echo 'selected="selected"'; } ?>>Hide page</option>
    </select>
    
  </div>
  <?php endif; ?>
<?php else: ?>
  <div class="misc-pub-section" style="border-bottom: none;">
  <?php _e('You do not have any memberships or subscriptions confiigured in your Cart66 Cloud account', 'cart66'); ?>
  </div>
<?php endif; ?>

