<ul id="cc_account_widget_list">
  <li id="cc_account_widget_list_item">

    <?php if($is_logged_in == true): ?>
      <div id="cc_account_widget_summary cc_logged_in">
        <?php echo $logged_in_message; ?>
      </div>

      <ul id="cc_cart_widget_links">
        <?php if($history_url): ?>
          <li class="cc_history_url">
            <a id="cc_account_widget_history" href='<?php echo $history_url; ?>'><?php _e('Order History', 'cart66'); ?></a>
          </li>
        <?php endif; ?>
        
        <?php if($profile_url): ?>
          <li class="cc_profile_url">
            <a id="cc_account_widget_profile" href='<?php echo $profile_url; ?>'><?php _e('Profile', 'cart66'); ?></a>
          </li>
        <?php endif; ?>

        <li class="cc_sign_out">
          <a id="cc_sign_out_link" href="<?php echo $sign_out_url; ?>"><?php _e('Sign out', 'cart66'); ?></a>
        </li>
      </ul>
    <?php else: ?>
      <div id="cc_account_widget_summary cc_logged_out">
        <?php echo $logged_out_message; ?>
      </div>

      <div class="cc_sign_in">
        <a id="cc_sign_in_link" href="<?php echo $sign_in_url; ?>"><?php _e('Sign in', 'cart66'); ?></a>
      </div>
    <?php endif; ?>

  </li>
</ul>

